### ISSUE TITLE
Improve HomePage

### ISSUE THREAD

**Issue by Pfed-prog** [dspytdao/PinSave-EVM#112]
Potential Improvements: pagination, improved Next Js rendering approach (pre-rendered images)

![image](https://user-images.githubusercontent.com/66903336/188256483-ae29341d-8364-4b01-bb7c-434442cd8aa0.png)

![image](https://user-images.githubusercontent.com/66903336/188256458-1e00235f-d309-4dfc-b6e7-3ca1c9899313.png)

**Comment by Pfed-prog** [comment]
Added ISG

**Comment by Pfed-prog** [comment]
- add multiple chains

**Comment by GregTrifan** [comment]
> Potential Improvements: pagination, improved Next Js rendering approach (pre-rendered images)
> 
> ![image](https://user-images.githubusercontent.com/66903336/188256483-ae29341d-8364-4b01-bb7c-434442cd8aa0.png)
> 
> ![image](https://user-images.githubusercontent.com/66903336/188256458-1e00235f-d309-4dfc-b6e7-3ca1c9899313.png)

Caching images might work out in the case of images, by either using the server itself or a 3rd party service

**Comment by Pfed-prog** [comment]
there is potential optimization on rendering batches progressively instead of whole list

**Comment by Pfed-prog** [comment]
the current implementation does not process the image link. Does it affect caching?

**Comment by Pfed-prog** [comment]
Added Multiple Chains on HomePage -> became slower. Can we optimize the page? Should we split the chains to different pages?
